"""
Session-025 tests: MultiAgentTrace new methods, F-005 fix verification,
topology API inconsistencies (F-073, F-074, F-075).

Focus areas:
- F-005 FIXED: checkagent init generates passing tests
- F-069 FIXED: LEAF_ERRORS blames leaf agents correctly
- F-071 FIXED: HandoffType now in checkagent.multiagent namespace
- New MultiAgentTrace methods: add_run, add_handoff, root_runs, get_children,
  detect_handoffs, handoff_chain, total_steps, total_tokens, total_duration_ms,
  succeeded, failed_runs, get_runs_by_agent
- F-073: get_children takes run_id, but other methods take agent_id
- F-074: add_run/add_handoff return None — not chainable
- F-075: handoff_chain uses explicit handoffs; root_runs/detect_handoffs use parent_run_id
"""

import pytest
import subprocess
import sys
import tempfile
import os
from pathlib import Path

from checkagent import AgentRun, AgentInput, Step
from checkagent.multiagent import (
    MultiAgentTrace,
    Handoff,
    BlameStrategy,
    BlameResult,
    assign_blame,
    assign_blame_ensemble,
    top_blamed_agent,
    HandoffType,
)


# ---------------------------------------------------------------------------
# Helper factories
# ---------------------------------------------------------------------------

def _make_run(agent_id: str, run_id: str | None = None, error: str | None = None,
               parent_run_id: str | None = None, steps: int = 0,
               prompt_tokens: int | None = None, completion_tokens: int | None = None,
               duration_ms: float | None = None) -> AgentRun:
    s = [Step(input_text=f"step{i}", output_text=f"out{i}") for i in range(steps)]
    return AgentRun(
        input=AgentInput(query=f"query for {agent_id}"),
        agent_id=agent_id,
        run_id=run_id,
        parent_run_id=parent_run_id,
        steps=s,
        final_output=None if error else f"output from {agent_id}",
        error=error,
        total_prompt_tokens=prompt_tokens,
        total_completion_tokens=completion_tokens,
        duration_ms=duration_ms,
    )


# ---------------------------------------------------------------------------
# F-005 FIXED: checkagent init generates passing tests
# ---------------------------------------------------------------------------

@pytest.mark.agent_test
def test_f005_fixed_init_generates_passing_tests():
    """F-005 FIXED: checkagent init now generates pyproject.toml with asyncio_mode and pythonpath."""
    with tempfile.TemporaryDirectory() as tmpdir:
        result = subprocess.run(
            ["checkagent", "init", tmpdir],
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0, f"checkagent init failed: {result.stderr}"
        pyproject = Path(tmpdir) / "pyproject.toml"
        assert pyproject.exists(), "pyproject.toml should be created by checkagent init"
        content = pyproject.read_text()
        assert "asyncio_mode" in content, "pyproject.toml should set asyncio_mode"
        assert "pythonpath" in content, "pyproject.toml should configure pythonpath"


@pytest.mark.agent_test
def test_f005_fixed_generated_tests_pass():
    """F-005 FIXED: tests generated by checkagent init pass immediately without any API keys."""
    with tempfile.TemporaryDirectory() as tmpdir:
        subprocess.run(["checkagent", "init", tmpdir], capture_output=True, check=True)
        result = subprocess.run(
            [sys.executable, "-m", "pytest", "tests/", "-v", "--tb=short"],
            capture_output=True,
            text=True,
            cwd=tmpdir,
        )
        assert result.returncode == 0, (
            f"Generated tests should pass immediately. stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
        )
        assert "passed" in result.stdout, "At least one test should pass"
        assert "failed" not in result.stdout, f"No tests should fail. stdout:\n{result.stdout}"


# ---------------------------------------------------------------------------
# F-069 FIXED: LEAF_ERRORS now correctly blames leaf agents
# ---------------------------------------------------------------------------

@pytest.mark.agent_test
def test_f069_fixed_leaf_errors_blames_leaf():
    """F-069 FIXED: LEAF_ERRORS blames the leaf agent (no outgoing handoffs)."""
    run_orch = _make_run("orchestrator", error="downstream failure")
    run_worker = _make_run("worker", error="root cause")
    trace = MultiAgentTrace(
        runs=[run_orch, run_worker],
        handoffs=[Handoff(from_agent_id="orchestrator", to_agent_id="worker")],
    )
    blame = assign_blame(trace, BlameStrategy.LEAF_ERRORS)
    assert blame is not None
    assert blame.agent_id == "worker", (
        f"LEAF_ERRORS should blame 'worker' (no outgoing handoffs), got '{blame.agent_id}'"
    )


@pytest.mark.agent_test
def test_f069_fixed_leaf_errors_deeper_chain():
    """LEAF_ERRORS correctly blames deepest leaf in A->B->C chain."""
    run_a = _make_run("a", error="propagated")
    run_b = _make_run("b", error="propagated")
    run_c = _make_run("c", error="original error")
    trace = MultiAgentTrace(
        runs=[run_a, run_b, run_c],
        handoffs=[
            Handoff(from_agent_id="a", to_agent_id="b"),
            Handoff(from_agent_id="b", to_agent_id="c"),
        ],
    )
    blame = assign_blame(trace, BlameStrategy.LEAF_ERRORS)
    assert blame is not None
    assert blame.agent_id == "c", (
        f"Expected 'c' (deepest leaf), got '{blame.agent_id}'"
    )


@pytest.mark.agent_test
def test_f069_fixed_leaf_errors_only_leaf_errored():
    """LEAF_ERRORS ignores orchestrators without errors, blames errored leaf."""
    run_orch = _make_run("orch", error=None)  # no error
    run_worker = _make_run("worker", error="disk full")
    trace = MultiAgentTrace(
        runs=[run_orch, run_worker],
        handoffs=[Handoff(from_agent_id="orch", to_agent_id="worker")],
    )
    blame = assign_blame(trace, BlameStrategy.LEAF_ERRORS)
    assert blame is not None
    assert blame.agent_id == "worker"


# ---------------------------------------------------------------------------
# F-071 FIXED: HandoffType in checkagent.multiagent namespace
# ---------------------------------------------------------------------------

@pytest.mark.agent_test
def test_f071_fixed_handoff_type_in_multiagent_namespace():
    """F-071 FIXED: HandoffType is now importable directly from checkagent.multiagent."""
    from checkagent.multiagent import HandoffType
    assert HandoffType is not None
    assert hasattr(HandoffType, "DELEGATION")
    assert hasattr(HandoffType, "RELAY")
    assert hasattr(HandoffType, "BROADCAST")


@pytest.mark.agent_test
def test_f071_fixed_handoff_type_values_accessible():
    """HandoffType values work correctly after namespace fix."""
    h = Handoff(
        from_agent_id="a",
        to_agent_id="b",
        handoff_type=HandoffType.RELAY,
    )
    assert h.handoff_type == HandoffType.RELAY
    assert h.handoff_type.value == "relay"


# ---------------------------------------------------------------------------
# MultiAgentTrace: aggregate properties
# ---------------------------------------------------------------------------

@pytest.mark.agent_test
def test_multiagent_trace_succeeded_all_ok():
    """MultiAgentTrace.succeeded is True when no runs have errors."""
    trace = MultiAgentTrace(runs=[_make_run("a"), _make_run("b")])
    assert trace.succeeded is True


@pytest.mark.agent_test
def test_multiagent_trace_succeeded_false_when_any_error():
    """MultiAgentTrace.succeeded is False when any run has an error."""
    trace = MultiAgentTrace(runs=[_make_run("a"), _make_run("b", error="oops")])
    assert trace.succeeded is False


@pytest.mark.agent_test
def test_multiagent_trace_failed_runs():
    """failed_runs returns only runs with errors."""
    trace = MultiAgentTrace(
        runs=[_make_run("a"), _make_run("b", error="fail"), _make_run("c", error="bad")]
    )
    failed = trace.failed_runs
    assert len(failed) == 2
    assert {r.agent_id for r in failed} == {"b", "c"}


@pytest.mark.agent_test
def test_multiagent_trace_total_steps():
    """total_steps sums steps across all runs."""
    trace = MultiAgentTrace(runs=[_make_run("a", steps=3), _make_run("b", steps=2)])
    assert trace.total_steps == 5


@pytest.mark.agent_test
def test_multiagent_trace_total_steps_empty():
    """total_steps is 0 for trace with no steps."""
    trace = MultiAgentTrace(runs=[_make_run("a"), _make_run("b")])
    assert trace.total_steps == 0


@pytest.mark.agent_test
def test_multiagent_trace_total_tokens():
    """total_tokens sums prompt+completion tokens across runs."""
    trace = MultiAgentTrace(runs=[
        _make_run("a", prompt_tokens=100, completion_tokens=50),
        _make_run("b", prompt_tokens=200, completion_tokens=100),
    ])
    assert trace.total_tokens == 450


@pytest.mark.agent_test
def test_multiagent_trace_total_tokens_none_when_missing():
    """total_tokens is None when no runs have token data."""
    trace = MultiAgentTrace(runs=[_make_run("a"), _make_run("b")])
    assert trace.total_tokens is None


@pytest.mark.agent_test
def test_multiagent_trace_total_duration_ms():
    """total_duration_ms sums duration across runs."""
    trace = MultiAgentTrace(runs=[
        _make_run("a", duration_ms=100.0),
        _make_run("b", duration_ms=200.0),
    ])
    assert trace.total_duration_ms == pytest.approx(300.0)


@pytest.mark.agent_test
def test_multiagent_trace_total_duration_ms_none_when_missing():
    """total_duration_ms is None when no duration set."""
    trace = MultiAgentTrace(runs=[_make_run("a"), _make_run("b")])
    assert trace.total_duration_ms is None


# ---------------------------------------------------------------------------
# MultiAgentTrace: topology methods (agent_ids, root_runs, detect_handoffs)
# ---------------------------------------------------------------------------

@pytest.mark.agent_test
def test_multiagent_trace_agent_ids():
    """agent_ids returns all agent IDs in the trace."""
    trace = MultiAgentTrace(runs=[_make_run("a"), _make_run("b"), _make_run("c")])
    assert set(trace.agent_ids) == {"a", "b", "c"}


@pytest.mark.agent_test
def test_multiagent_trace_root_runs_uses_parent_run_id():
    """root_runs returns runs with no parent_run_id set."""
    run_a = _make_run("a", run_id="run-a")
    run_b = _make_run("b", run_id="run-b", parent_run_id="run-a")
    run_c = _make_run("c", run_id="run-c", parent_run_id="run-a")
    trace = MultiAgentTrace(runs=[run_a, run_b, run_c])
    roots = trace.root_runs
    assert len(roots) == 1
    assert roots[0].agent_id == "a"


@pytest.mark.agent_test
def test_multiagent_trace_root_runs_all_roots_when_no_parent():
    """root_runs returns all runs when none have parent_run_id set."""
    trace = MultiAgentTrace(runs=[_make_run("a"), _make_run("b")])
    # All runs are "roots" when parent_run_id not set
    assert len(trace.root_runs) == 2


@pytest.mark.agent_test
def test_multiagent_trace_detect_handoffs_from_parent_run_id():
    """detect_handoffs() auto-generates Handoff objects from parent_run_id relationships."""
    run_a = _make_run("a", run_id="run-a")
    run_b = _make_run("b", run_id="run-b", parent_run_id="run-a")
    run_c = _make_run("c", run_id="run-c", parent_run_id="run-a")
    trace = MultiAgentTrace(runs=[run_a, run_b, run_c])
    detected = trace.detect_handoffs()
    assert len(detected) == 2
    agent_ids_from = {h.from_agent_id for h in detected}
    agent_ids_to = {h.to_agent_id for h in detected}
    assert "a" in agent_ids_from
    assert {"b", "c"} == agent_ids_to


@pytest.mark.agent_test
def test_multiagent_trace_detect_handoffs_empty_when_no_parent_run_id():
    """detect_handoffs() returns empty list when no parent_run_id is set on any run."""
    trace = MultiAgentTrace(
        runs=[_make_run("a"), _make_run("b")],
        handoffs=[Handoff(from_agent_id="a", to_agent_id="b")],
    )
    # detect_handoffs uses parent_run_id, not the explicit handoffs list
    detected = trace.detect_handoffs()
    assert len(detected) == 0


@pytest.mark.agent_test
def test_multiagent_trace_get_runs_by_agent():
    """get_runs_by_agent returns all runs for a given agent_id."""
    run1 = _make_run("a", run_id="run-a-1")
    run2 = _make_run("a", run_id="run-a-2")  # same agent, second run
    run3 = _make_run("b", run_id="run-b")
    trace = MultiAgentTrace(runs=[run1, run2, run3])
    runs_for_a = trace.get_runs_by_agent("a")
    assert len(runs_for_a) == 2
    assert all(r.agent_id == "a" for r in runs_for_a)


@pytest.mark.agent_test
def test_multiagent_trace_get_handoffs_from():
    """get_handoffs_from returns outgoing handoffs for an agent_id."""
    trace = MultiAgentTrace(
        runs=[_make_run("a"), _make_run("b"), _make_run("c")],
        handoffs=[
            Handoff(from_agent_id="a", to_agent_id="b"),
            Handoff(from_agent_id="a", to_agent_id="c"),
        ],
    )
    handoffs = trace.get_handoffs_from("a")
    assert len(handoffs) == 2
    assert all(h.from_agent_id == "a" for h in handoffs)


@pytest.mark.agent_test
def test_multiagent_trace_get_handoffs_to():
    """get_handoffs_to returns incoming handoffs for an agent_id."""
    trace = MultiAgentTrace(
        runs=[_make_run("a"), _make_run("b"), _make_run("c")],
        handoffs=[
            Handoff(from_agent_id="a", to_agent_id="c"),
            Handoff(from_agent_id="b", to_agent_id="c"),
        ],
    )
    handoffs = trace.get_handoffs_to("c")
    assert len(handoffs) == 2
    assert all(h.to_agent_id == "c" for h in handoffs)


@pytest.mark.agent_test
def test_multiagent_trace_handoff_chain():
    """handoff_chain returns topological ordering of agents from explicit handoffs."""
    trace = MultiAgentTrace(
        runs=[_make_run("a"), _make_run("b"), _make_run("c")],
        handoffs=[
            Handoff(from_agent_id="a", to_agent_id="b"),
            Handoff(from_agent_id="b", to_agent_id="c"),
        ],
    )
    chain = trace.handoff_chain()
    assert chain == ["a", "b", "c"]


# ---------------------------------------------------------------------------
# F-073: get_children takes run_id, not agent_id — API inconsistency
# ---------------------------------------------------------------------------

@pytest.mark.agent_test
def test_f073_get_children_takes_run_id_not_agent_id():
    """F-073: get_children(run_id) uses run_id — NOT agent_id.

    All other topology methods (get_handoffs_from, get_handoffs_to, get_runs_by_agent)
    take agent_id. get_children is the odd one out.
    """
    run_a = _make_run("agent-a", run_id="run-a")
    run_b = _make_run("agent-b", run_id="run-b", parent_run_id="run-a")
    trace = MultiAgentTrace(runs=[run_a, run_b])

    # Passing agent_id to get_children returns empty — this is the API trap
    children_by_agent_id = trace.get_children("agent-a")
    assert children_by_agent_id == [], (
        "F-073: get_children('agent-a') returns empty — it expects run_id, not agent_id"
    )

    # Correct usage: pass run_id
    children_by_run_id = trace.get_children("run-a")
    assert len(children_by_run_id) == 1
    assert children_by_run_id[0].agent_id == "agent-b"


@pytest.mark.agent_test
def test_f073_inconsistency_get_children_vs_get_runs_by_agent():
    """F-073: API inconsistency — get_children takes run_id, get_runs_by_agent takes agent_id.

    Users who learn get_runs_by_agent(agent_id) will naturally try get_children(agent_id),
    which silently returns an empty list.
    """
    run_a = _make_run("my-orchestrator", run_id="run-orch-001")
    run_b = _make_run("my-worker", run_id="run-worker-001", parent_run_id="run-orch-001")
    trace = MultiAgentTrace(runs=[run_a, run_b])

    # get_runs_by_agent uses agent_id
    result_by_agent = trace.get_runs_by_agent("my-orchestrator")
    assert len(result_by_agent) == 1

    # get_children requires run_id — not agent_id like everything else
    result_children_agent = trace.get_children("my-orchestrator")  # wrong key type
    result_children_run = trace.get_children("run-orch-001")  # correct key type

    assert result_children_agent == [], "get_children with agent_id silently returns []"
    assert len(result_children_run) == 1, "get_children with run_id returns correctly"


# ---------------------------------------------------------------------------
# F-074: add_run and add_handoff return None — not chainable
# ---------------------------------------------------------------------------

@pytest.mark.agent_test
def test_f074_add_run_returns_none():
    """F-074 FIXED: add_run() now returns self — builder chaining works."""
    trace = MultiAgentTrace()
    result = trace.add_run(_make_run("a"))
    assert result is trace, (
        "F-074 FIXED: add_run now returns self for builder chaining."
    )
    # Chaining works
    trace2 = MultiAgentTrace()
    trace2.add_run(_make_run("a")).add_run(_make_run("b"))
    assert len(trace2.runs) == 2


@pytest.mark.agent_test
def test_f074_add_handoff_returns_none():
    """F-074 FIXED: add_handoff() now returns self — builder chaining works."""
    trace = MultiAgentTrace()
    result = trace.add_handoff(Handoff(from_agent_id="a", to_agent_id="b"))
    assert result is trace, (
        "F-074 FIXED: add_handoff now returns self for builder chaining."
    )
    # Chaining add_run and add_handoff
    trace2 = MultiAgentTrace()
    trace2.add_run(_make_run("a")).add_run(_make_run("b")).add_handoff(Handoff(from_agent_id="a", to_agent_id="b"))
    assert len(trace2.runs) == 2
    assert len(trace2.handoffs) == 1


@pytest.mark.agent_test
def test_f074_add_run_still_mutates_correctly():
    """Workaround: add_run/add_handoff do mutate the trace even though they return None."""
    trace = MultiAgentTrace()
    trace.add_run(_make_run("a", run_id="run-a"))
    trace.add_run(_make_run("b", run_id="run-b", parent_run_id="run-a"))
    trace.add_handoff(Handoff(from_agent_id="a", to_agent_id="b"))
    assert len(trace.runs) == 2
    assert len(trace.handoffs) == 1
    assert trace.agent_ids == ["a", "b"]


# ---------------------------------------------------------------------------
# F-075: handoff_chain vs root_runs / detect_handoffs use different topology sources
# ---------------------------------------------------------------------------

@pytest.mark.agent_test
def test_f075_handoff_chain_uses_explicit_handoffs_not_parent_run_id():
    """F-075: handoff_chain() uses explicit handoffs; root_runs uses parent_run_id.

    Two topology representations exist: explicit handoffs list and parent_run_id.
    Methods use different sources:
    - handoff_chain() → uses handoffs list
    - root_runs → uses parent_run_id
    - detect_handoffs() → uses parent_run_id (read-only since F-076 fix)
    - get_children() → uses parent_run_id

    apply_detected_handoffs() bridges the gap (F-076 fix also added this method).
    """
    # Set parent_run_id linkage but NOT explicit handoffs
    run_a = _make_run("a", run_id="run-a")
    run_b = _make_run("b", run_id="run-b", parent_run_id="run-a")
    trace = MultiAgentTrace(runs=[run_a, run_b])

    chain_before = trace.handoff_chain()
    assert chain_before == [], (
        "F-075: handoff_chain() returns [] when no explicit handoffs are set, "
        "even if parent_run_id relationships exist"
    )

    # parent_run_id topology: root_runs sees the relationship
    assert len(trace.root_runs) == 1  # only 'a' is a root


@pytest.mark.agent_test
def test_f076_detect_handoffs_mutates_trace_handoffs():
    """F-076 FIXED: detect_handoffs() is now read-only — does NOT mutate trace.handoffs."""
    run_a = _make_run("a", run_id="run-a")
    run_b = _make_run("b", run_id="run-b", parent_run_id="run-a")
    trace = MultiAgentTrace(runs=[run_a, run_b])

    assert len(trace.handoffs) == 0, "Should start empty"

    # First call — should return detected handoffs without mutating
    detected1 = trace.detect_handoffs()
    assert len(detected1) == 1
    assert len(trace.handoffs) == 0, "F-076 FIXED: detect_handoffs() no longer mutates trace.handoffs"

    # Second call — should still return the same result, not double
    detected2 = trace.detect_handoffs()
    assert len(trace.handoffs) == 0, "F-076 FIXED: calling twice still doesn't mutate"
    assert len(detected2) == 1


@pytest.mark.agent_test
def test_f076_detect_handoffs_poisons_handoff_chain():
    """F-076 FIXED: detect_handoffs() no longer poisons handoff_chain().

    After the fix, detect_handoffs() is read-only so handoff_chain() remains
    empty if no explicit handoffs were added.
    """
    run_a = _make_run("a", run_id="run-a")
    run_b = _make_run("b", run_id="run-b", parent_run_id="run-a")
    trace = MultiAgentTrace(runs=[run_a, run_b])

    # Without detect_handoffs: handoff_chain is empty
    assert trace.handoff_chain() == []

    # After detect_handoffs: handoff_chain is STILL empty (no longer mutated)
    trace.detect_handoffs()
    chain = trace.handoff_chain()
    assert chain == [], (
        "F-076 FIXED: handoff_chain() stays empty after detect_handoffs() — no mutation"
    )


@pytest.mark.agent_test
def test_f075_consistent_when_both_sources_set():
    """Workaround: setting both explicit handoffs and parent_run_id gives consistent results."""
    run_a = _make_run("a", run_id="run-a")
    run_b = _make_run("b", run_id="run-b", parent_run_id="run-a")
    trace = MultiAgentTrace(
        runs=[run_a, run_b],
        handoffs=[Handoff(from_agent_id="a", to_agent_id="b", from_run_id="run-a", to_run_id="run-b")],
    )

    # Both sources now agree
    assert len(trace.root_runs) == 1
    assert trace.handoff_chain() == ["a", "b"]
    assert len(trace.detect_handoffs()) == 1


# ---------------------------------------------------------------------------
# MultiAgentTrace: complex blame scenarios post-F-069-fix
# ---------------------------------------------------------------------------

@pytest.mark.agent_test
def test_leaf_errors_broadcast_fan_out():
    """LEAF_ERRORS handles fan-out: orchestrator delegates to 3 workers, 2 fail."""
    run_orch = _make_run("orch", error=None)
    run_w1 = _make_run("worker1", error="timeout")
    run_w2 = _make_run("worker2", error=None)  # succeeded
    run_w3 = _make_run("worker3", error="bad gateway")
    trace = MultiAgentTrace(
        runs=[run_orch, run_w1, run_w2, run_w3],
        handoffs=[
            Handoff(from_agent_id="orch", to_agent_id="worker1"),
            Handoff(from_agent_id="orch", to_agent_id="worker2"),
            Handoff(from_agent_id="orch", to_agent_id="worker3"),
        ],
    )
    blame = assign_blame(trace, BlameStrategy.LEAF_ERRORS)
    # Should blame one of the failed leaf workers
    assert blame is not None
    assert blame.agent_id in {"worker1", "worker3"}
    assert "orch" != blame.agent_id


@pytest.mark.agent_test
def test_top_blamed_agent_post_leaf_fix():
    """top_blamed_agent tie-breaks when strategies split evenly.

    In a 2-agent trace (orch -> worker), both erroring:
    - FIRST_ERROR blames orch (first in runs list)
    - MOST_STEPS blames orch (0 steps each, first-in-list wins)
    - LAST_AGENT blames worker (last in runs list)
    - LEAF_ERRORS blames worker (correct: no outgoing handoffs)

    Result: 2 vs 2 tie — orch wins due to FIRST_ERROR + MOST_STEPS.
    (Before F-069 fix, LEAF_ERRORS also blamed orch, giving orch 3 votes.)
    """
    run_orch = _make_run("orch", error="delegated failure")
    run_worker = _make_run("worker", error="root cause")
    trace = MultiAgentTrace(
        runs=[run_orch, run_worker],
        handoffs=[Handoff(from_agent_id="orch", to_agent_id="worker")],
    )
    results = assign_blame_ensemble(trace)
    orch_votes = sum(1 for r in results if r.agent_id == "orch")
    worker_votes = sum(1 for r in results if r.agent_id == "worker")
    # After F-069 fix: worker gets LEAF_ERRORS + LAST_AGENT = 2 votes
    assert worker_votes == 2, f"Worker should get 2 votes post-F-069-fix, got {worker_votes}"
    # It's a tie (2:2) — top_blamed_agent returns one of them
    top = top_blamed_agent(trace)
    assert top is not None
    assert top.agent_id in {"orch", "worker"}


@pytest.mark.agent_test
def test_assign_blame_ensemble_after_leaf_fix():
    """assign_blame_ensemble now includes correct LEAF_ERRORS results."""
    run_orch = _make_run("orch", error="downstream")
    run_worker = _make_run("worker", error="disk full")
    trace = MultiAgentTrace(
        runs=[run_orch, run_worker],
        handoffs=[Handoff(from_agent_id="orch", to_agent_id="worker")],
    )
    results = assign_blame_ensemble(trace)
    leaf_result = next((r for r in results if r.strategy == BlameStrategy.LEAF_ERRORS), None)
    assert leaf_result is not None
    assert leaf_result.agent_id == "worker", (
        f"LEAF_ERRORS in ensemble should blame 'worker', got '{leaf_result.agent_id}'"
    )
